#配置端口号和访问前缀
server:
  port: 8080
  servlet:
    context-path: /ybb

#数据库配置
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/ybb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: sasa
      driverClassName: com.mysql.cj.jdbc.Driver

#配置日志
logging:
  #配置日志文件路径
  level:
    org.springfromework.web: info
  file: /opt/TomCat8.5/apache-tomcat-8.5.16/logs/ybb.log

jedis :
  pool :
    host : 101.132.117.185
    port : 6379
    password: ""
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000



management:
  endpoints:
    web:
      exposure:
        include: "*" # * 在yaml 文件属于关键字
  server:
    port: 8181

  endpoint:
    shutdown:
      enabled: true